from django.urls import path
from .views import (
    ItemListView,
    AddToCartView,
    OrderDetailView,
    AddCouponView,
    PaymentView,
    ItemDetailView,
    OrderItemDeleteView,
    OrderQuantityUpdateView,
    AddressListView,
    AddressCreateView,
    AddressUpdateView,
    AddressDeleteView,
    CountryListView,
    RegionListView,
    CityListView,
    UserIDView,
    OrderHistoryView,
    )

urlpatterns = [
    path('products/', ItemListView.as_view(), name='product-list'),
    path('products/<pk>/', ItemDetailView.as_view(), name='product-detail'),
    path('add-to-cart/', AddToCartView.as_view(), name='add-to-cart'),
    path('order-summary/', OrderDetailView.as_view(), name='order-summary'),
    path('order-items/<pk>/delete/', OrderItemDeleteView.as_view(), name='order-item-delete'),
    path('order-items/update-quantity/', OrderQuantityUpdateView.as_view(), name='order-item-update-quantity'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('addresses/', AddressListView.as_view(), name='address-list'),
    path('checkout/', PaymentView.as_view(), name='checkout'),
    path('order-history/', OrderHistoryView.as_view(), name='order-history'),
    path('user-id/', UserIDView.as_view(), name='user-id'),
    path('addresses/create/', AddressCreateView.as_view(), name='address-create'),
    path('addresses/<pk>/update/', AddressUpdateView.as_view(), name='address-update'),
    path('addresses/<pk>/delete/', AddressDeleteView.as_view(), name='address-delete'),
    path('countries/', CountryListView.as_view(), name='countries'),
    path('regions/', RegionListView.as_view(), name='regions'),
    path('cities/', CityListView.as_view(), name='cities'),
]
