# Generated by Django 3.0.5 on 2020-04-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem_item_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='region',
        ),
    ]
