# Generated by Django 3.0.5 on 2020-04-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200426_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
