# Generated by Django 3.0.5 on 2020-05-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200427_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('FP', 'Fresh Produce'), ('BK', 'Bakery'), ('BG', 'Beans and Grains'), ('NS', 'Nuts and Seeds'), ('DF', 'Dried Fruit'), ('PI', 'Pantry Items'), ('BA', 'Baking'), ('SH', 'Spices and Herbs'), ('SK', 'Snacking')], max_length=2),
        ),
    ]
